### ISSUE TITLE
Add build script to simply building/testing like we do for the Max implementation

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaCore#373]

**Comment by tap** [comment]
Hi @avilleret -- I'm assigning to you now for a code review.  If you are happy then feel free to close it.

I decided just to be simple for now, but if anyone is feeling like it should be more flexible (like the Max build.sh) then I certainly have no objections.

Merci!

**Comment by avilleret** [comment]
I made some changes to make it works on Linux and I reduce the number of CPU to use.
16 is good on my Macpro but could burn my laptop (or at least cut the music stream which unacceptable :-) )

You could split this script with one version per OS and add lots of options, but i close the issue now since it is working.

**Comment by tap** [comment]
fabulous -- thanks!
