### ISSUE TITLE
wrong formulas in polar / spherical dataspaces

### ISSUE THREAD

**Issue by jcelerier** [jamoma/JamomaCore#399]
e.g.

    output[0] = atan2(xx, yy) * kTTRadiansToDegrees; //a
    output[1] = pow(((xx * xx) + (yy * yy)), 0.5); //distance

I think that it should be atan2(yy, xx): the "naive math" formula is 

x = r cos theta
y = r sin theta

=> 

r = sqrt(...)
theta = arctan(y/x) 

and arctan(y/x) ~ atan2(y, x)

**Comment by lossius** [comment]
I'm sure that if you review the code for this dataspace you'll find oddities several places. The reason is because we are using non-standard mathematical conversions:

- Cartesian coordinates: x to right, y forward, z upwards
- Polar: Navigational system with 0 degrees to the north (forward), +90 to the east (right), -90 to the west (left) and 180 south (back).

This makes the formulas for conversions between Cartesian and Polar different to what you'd expect in a maths class.

**Comment by jcelerier** [comment]
good to know, thanks! are there other conventions used in the dataspaces documented somewhere ?
